### ISSUE TITLE
Question regarding alignment generation

### ISSUE THREAD

**Issue by Sreyan88** [tal-ai/FG_CME#1]
Hi there!

Great paper and great code! I just have a small question regarding the binary alignment matrix part of the code and paper.

In this part in the main function:

```
align_info = open(align_path, 'r').readlines()[1:-1] # get rid off the head and tail info
        align_info = [re.split('\ +', x) for x in align_info]
        align_info = [(x[-1].strip('\n').split('(')[0].lower(),int(x[1]),int(x[2])) for x in align_info]
        # For the silence probably we can make some use
        align_info = [x for x in align_info if x[0] not in ['<s>','<sil>','</s>']]
        align_input = []
        for _, begin_time, end_time in align_info:
            begin_idx = int(begin_time * 0.01 / 0.01)
            end_idx = int(end_time * 0.01 / 0.01) + 1
            align_slice = torch.zeros(audio_input.size(0))
            align_slice[begin_idx:end_idx] = 1.0
            align_input.append(align_slice[None,:])
        align_input = torch.cat(align_input, dim=0)
```
If align info is a generic alignment file with timestamps based on seconds, then I am not sure how `begin_idx = int(begin_time * 0.01 / 0.01)` would work. According to my intuition this should probably be:

```
begin_idx = int(begin_time * sampling_rate / frame_step)
```

Same question for `end_idx`.

Please let me know if there is something wrong in my understanding!

Thank You

**Comment by hzlihang99** [comment]
Hi,

Thanks for your appreciation of our work. And I am sorry that I didn't leave too much comments for some details for our code.

For the alignment, we use the Montreal-Force-Aligner(https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner). The output timestamps for each token(word) is saved as frame index, e.g.,

 SFrm  EFrm    SegAScr Word
 0     6     300581 <s>
 7    71    3580522 <sil>
 72    94    -819956 LIKE
 95   137     -99401 WHAT(2)
 138   259    5265447 <sil>
 260   276    -623939 LIKE
 277   282    -161498 A
 283   288     -60769 <sil>
 289   311    -668106 BIRTH
 312   375    -988951 CERTIFICATE(6)
 376   391     274192 <sil>
 392   408     557909 </s>

The default frame step for Montreal-Force-Aligner is set as 0.01, and to make it compatible with our model's frame step, we choose to use the formula: frame_index_by_Force_Aligner * Frame_Step_of_Force_Aligner / Frame_Step_of_Ours. And this makes our code looks like int(begin_time * 0.01 / 0.01).

Hope this can be helpful for you.

Best

**Comment by Sreyan88** [comment]
hi @hzlihang99 ,

Thank you for your answer. I had one more question. I wanted to know the significance of passing the alignment matrix through nn.AvgPool2d(). Since the ultimate goal is to find out relevant frames for each word and do mean + max pool I was just thinking how an average pool over the alignment matric would affect the alignments.

Thank You!

**Comment by hzlihang99** [comment]
Hi @Sreyan88 

It is a good question. The reason for us to apply the mean-pooling strategy to the alignment matrix is because we use the 1-d convolution layer to the frame-level audio inputs. For the step-wise representations generated from convolution layers, they may not be perfectly aligned with the original alignment results, especially when the stride size is not 1. 

To solve that issue, we apply the meaning-pooling layer to ensure the shape of alignment matrix and audio representation matrix are compatible with each other for the later process.

Hope this can be helpful for you.

Best
